import React from 'react'
import {
  MapPin,
  ArrowRight,
  Phone,
  Clock,
  ShoppingBag,
  User,
  Users,
  UserPlus,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  DollarSign,
  AlertCircle,
  AlertTriangle,
  Sliders,
  Truck,
} from 'react-feather'

export const iconMap = {
  RefreshCw: <RefreshCw size={null} />,
  MapPin: <MapPin size={null} />,
  Phone: <Phone size={null} />,
  Clock: <Clock size={null} />,
  ArrowLeft: <ArrowLeft size={null} />,
  ArrowRight: <ArrowRight size={null} />,
  ChevronLeft: <ChevronLeft size={null} />,
  ChevronRight: <ChevronRight size={null} />,
  ChevronUp: <ChevronUp size={null} />,
  ChevronDown: <ChevronDown size={null} />,
  ShoppingBag: <ShoppingBag size={null} />,
  DollarSign: <DollarSign size={null} />,
  User: <User size={null} />,
  Users: <Users size={null} />,
  UserPlus: <UserPlus size={null} />,
  AlertCircle: <AlertCircle size={null} />,
  AlertTriangle: <AlertTriangle size={null} />,
  Sliders: <Sliders size={null} />,
  Truck: <Truck size={null} />,
}
