import React from 'react'
import {
  MapPin,
  Map,
  ArrowRight,
  Phone,
  Clock,
  ShoppingBag,
  User,
  Users,
  UserPlus,
  RefreshCw,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  DollarSign,
  AlertCircle,
  AlertTriangle,
  Sliders,
  Truck,
  Gift,
  Delete,
  XCircle,
  PlusCircle,
  Check,
  CheckCircle,
  CreditCard,
  Home,
  Grid,
  Navigation,
  FileText,
  ExternalLink,
  Star,
  Edit,
  Heart,
  Trash2,
  Flag,
  Plus,
  Minus,
  UserX,
  Calendar,
  Slash,
  Coffee,
  Info,
  Save,
  Clipboard,
} from 'react-feather'

const iconMap = {
  AlertCircle: <AlertCircle size={null} />,
  AlertTriangle: <AlertTriangle size={null} />,
  ArrowLeft: <ArrowLeft size={null} />,
  ArrowRight: <ArrowRight size={null} />,
  Calendar: <Calendar size={null} />,
  Check: <Check size={null} />,
  CheckCircle: <CheckCircle size={null} />,
  ChevronLeft: <ChevronLeft size={null} />,
  ChevronRight: <ChevronRight size={null} />,
  ChevronUp: <ChevronUp size={null} />,
  ChevronDown: <ChevronDown size={null} />,
  Clipboard: <Clipboard size={null} />,
  Coffee: <Coffee size={null} />,
  Clock: <Clock size={null} />,
  CreditCard: <CreditCard size={null} />,
  Delete: <Delete size={null} />,
  DollarSign: <DollarSign size={null} />,
  Edit: <Edit size={null} />,
  ExternalLink: <ExternalLink size={null} />,
  Flag: <Flag size={null} />,
  FileText: <FileText size={null} />,
  Gift: <Gift size={null} />,
  Grid: <Grid size={null} />,
  Heart: <Heart size={null} />,
  Home: <Home size={null} />,
  Info: <Info size={null} />,
  Phone: <Phone size={null} />,
  Plus: <Plus size={null} />,
  PlusCircle: <PlusCircle size={null} />,
  Map: <Map size={null} />,
  MapPin: <MapPin size={null} />,
  Minus: <Minus size={null} />,
  Navigation: <Navigation size={null} />,
  RefreshCw: <RefreshCw size={null} />,
  Save: <Save size={null} />,
  ShoppingBag: <ShoppingBag size={null} />,
  Slash: <Slash size={null} />,
  Sliders: <Sliders size={null} />,
  Star: <Star size={null} />,
  Trash2: <Trash2 size={null} />,
  Truck: <Truck size={null} />,
  User: <User size={null} />,
  UserPlus: <UserPlus size={null} />,
  UserX: <UserX size={null} />,
  Users: <Users size={null} />,
  XCircle: <XCircle size={null} />,
}

export default iconMap
